import React, {useEffect, useState} from 'react';
import MoveUpPurchase from './MoveUpPurchase';
import {SafeAreaView, View, Text, TextInput, Pressable, FlatList, StyleSheet, ActivityIndicator} from 'react-native';

type Screen='login'|'home'|'ranking'|'profile'|'moveup'|'notifications';
type User={nickname:string;rank:number;credits:number};
type Row={rank:number;nickname:string};
const API='https://ewr.onrender.com/api/v1';

async function api(path:string, init:RequestInit={}, token?:string){const r=await fetch(API+path,{...init,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(init.headers||{})}}); if(!r.ok) throw new Error(`HTTP ${r.status}`); return r.json();}

export default function App(){
 const [screen,setScreen]=useState<Screen>('login'); const [token,setToken]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [user,setUser]=useState<User|null>(null); const [ranking,setRanking]=useState<Row[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const load=async()=>{if(!token)return; try{setBusy(true); const [u,r]=await Promise.all([api('/me',{},token),api('/ranking',{},token)]); setUser({nickname:u.nickname,rank:u.rank,credits:u.credits}); setRanking(r);}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{if(token)load()},[token]);
 const login=async()=>{try{setBusy(true);setError('');const x=await api('/login',{method:'POST',body:JSON.stringify({email,password})});setToken(x.access_token);setScreen('home')}catch(e:any){setError('Login failed')}finally{setBusy(false)}};
 if(!token) return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.logo}>🌍 EARTH</Text><Text style={s.title}>WORLD RANKING</Text><Text style={s.tag}>ONE WORLD. ONE RANKING.</Text><TextInput style={s.input} placeholder="Email" autoCapitalize="none" value={email} onChangeText={setEmail}/><TextInput style={s.input} placeholder="Password" secureTextEntry value={password} onChangeText={setPassword}/><Button text={busy?'Signing in…':'LOGIN'} onPress={login} disabled={busy}/>{error?<Text style={s.error}>{error}</Text>:null}<Text style={s.muted}>Your payment data and credits are private.</Text></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><View style={s.header}><Text style={s.logoSmall}>🌍 EWR</Text><Pressable onPress={()=>{setToken('');setUser(null)}}><Text>Log out</Text></Pressable></View>
 {screen==='home'&&<View style={s.page}><Text style={s.kicker}>YOUR GLOBAL POSITION</Text><Text style={s.rank}>#{user?.rank??'—'}</Text><Text style={s.name}>@{user?.nickname}</Text><Button text="MOVE UP" onPress={()=>setScreen('moveup')}/><Button text="GLOBAL RANKING" onPress={()=>setScreen('ranking')} secondary/><Button text="PROFILE" onPress={()=>setScreen('profile')} secondary/></View>}
 {screen==='ranking'&&<List title="GLOBAL RANKING" rows={ranking} own={user?.nickname} back={()=>setScreen('home')}/>} 
 {screen==='profile'&&<View style={s.page}><Text style={s.kicker}>PROFILE</Text><Text style={s.name}>@{user?.nickname}</Text><Text style={s.rank}>#{user?.rank}</Text><Text style={s.private}>Private credits: {user?.credits}</Text><Button text="MOVE UP" onPress={()=>setScreen('moveup')}/><Button text="BACK" onPress={()=>setScreen('home')} secondary/></View>}
 {screen==='moveup'&&<View style={s.page}><Text style={s.kicker}>MOVE UP</Text><Text style={s.name}>Current position #{user?.rank}</Text><Text style={s.private}>Choose an EWR Credits package.</Text><MoveUpPurchase token={token} apiBase={API} onSuccess={()=>{load();setScreen('home')}}/><Button text="BACK" onPress={()=>setScreen('home')} secondary/></View>}
 {screen==='notifications'&&<View style={s.page}><Text style={s.kicker}>NOTIFICATIONS</Text><Text style={s.private}>No new notifications.</Text><Button text="BACK" onPress={()=>setScreen('home')} secondary/></View>}
 </SafeAreaView>
}
function List({title,rows,own,back}:{title:string;rows:Row[];own?:string;back:()=>void}){return <View style={s.page}><Text style={s.kicker}>{title}</Text><FlatList data={rows} keyExtractor={x=>String(x.rank)} renderItem={({item})=><View style={[s.row,item.nickname===own&&s.own]}><Text style={s.r}>{item.rank}</Text><Text style={s.nick}>@{item.nickname}</Text></View>}/><Button text="BACK" onPress={back} secondary/></View>}
function Button({text,onPress,secondary,disabled}:{text:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,secondary&&s.secondary,disabled&&s.disabled]}><Text style={s.buttonText}>{text}</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#fff'},center:{flex:1,justifyContent:'center',padding:28},page:{flex:1,padding:24},header:{height:58,paddingHorizontal:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#eee'},logo:{fontSize:34,fontWeight:'800',textAlign:'center'},logoSmall:{fontSize:20,fontWeight:'800'},title:{fontSize:25,fontWeight:'800',textAlign:'center'},tag:{textAlign:'center',letterSpacing:2,marginBottom:36,color:'#666'},input:{borderWidth:1,borderColor:'#ddd',padding:14,marginBottom:12,fontSize:16},button:{backgroundColor:'#111',padding:16,marginTop:12,alignItems:'center'},secondary:{backgroundColor:'#eee'},disabled:{opacity:.5},buttonText:{fontWeight:'800',color:'#fff'},kicker:{fontSize:13,letterSpacing:2,color:'#777',marginBottom:12},rank:{fontSize:72,fontWeight:'900',marginBottom:4},name:{fontSize:22,fontWeight:'700',marginBottom:24},private:{fontSize:17,marginVertical:12},muted:{color:'#777',marginTop:20,textAlign:'center'},error:{color:'#b00020',marginTop:12,textAlign:'center'},row:{flexDirection:'row',padding:16,borderBottomWidth:1,borderBottomColor:'#eee'},own:{borderWidth:2,borderColor:'#111',borderRadius:10},r:{width:70,fontWeight:'800'},nick:{fontSize:16,fontWeight:'600'}});
